### ISSUE TITLE
design feedback

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-leaflet-routing#1]
awesome work @patrickarlt 
looking at your proposal, i have the following ideas...
1. in general, i haven't been able to think of a good reason (yet) to 'stray' from the original API design.  the important thing it seems to me is rather is to hide as many optional parameters as possible from developers to make the bulk of use cases as intuitive as possible.
2. it would be fun to design so that async is implemented automatically when necessary, but i think the sync services will serve 95% of use cases as even sync routing accepts up to 150 stops and can run for 90 seconds at a time.  additionally, i'm wondering whether we can make a better decision than the developer (if given control to set async themselves optionally) because time to execute is not purely a function of the number of stops, but rather a combination of the number, distance apart, whether optimization is required, and the setting of other parameters like whether or not hierarchy is used.

to me it seems straightforward enough for us to assume sync, give the option to advanced developers to override and then do the work in the back-end to ensure that they are passed back the same results (rather than forcing them to do their own polling)
1. traffic seems to me like an interesting thing to incorporate into the route solution itself, but not visually important as anything other than a backdrop.  granted, i fully admit that i am a pretty unimaginative fellow.
2. live updates are cool, but i guess i fear that they open up the door to an expectation/hope that we'll be able to modify intermediate stops as well.  all cool things, but quite a bit of work.
3. robust samples (including turning addresses into stops) seem pretty essential.
4. i assume we will get a substantial number of requests and i think it would be pretty awesome/useful if developers could subsitute their own network analyst services via an optional constructor parameter.

**Comment by patrickarlt** [comment]
> in general, i haven't been able to think of a good reason (yet) to 'stray' from the original API design.

I agree one of the things that makes Esri Leaflet great is the simplicity of the Esri Leaflt API relative to the actual REST APIs. I definitely want to make this easy to use but the real power of the routing services comes from the fact that you CAN define all this stuff like u-turns, curb approaches, restrictions and barriers. Without exposing these options this really isn't any better then any existing routing APIs.

The goal of this design phase is to try to nail the balance of features and simplicity that will make this useful.

Maybe I should add a "Design Goals" section to the document to highlight the fact this has to be both powerful and simple.

> to me it seems straightforward enough for us to assume sync, give the option to advanced developers to override and then do the work in the back-end to ensure that they are passed back the same results 

I'm not opposed to having `useAsync: true` option on all of these especially if we base this on your geoprocessing task which does all the work. But I think the API should always work no matter what. IF i pass 151 stops should I have to get an error or warning that tells me to set an option? Shouldn't it "just work"?

> traffic seems to me like an interesting thing to incorporate into the route solution itself, but not visually important as anything other than a backdrop. granted, i fully admit that i am a pretty unimaginative fellow.

I've been trying to think of more interesting things to do with the traffic service then just display it. Querying the traffic incidents seems like the obvious thing to do. Maybe the traffic layer shouldn't be part of this discussion and can be a separate plugin?

> live updates are cool, but i guess i fear that they open up the door to an expectation/hope that we'll be able to modify intermediate stops as well. all cool things, but quite a bit of work.

I didn't even think about being able to update existing stops. Maybe using the named stop route like this

``` js
var esrihq = new L.esri.Routing.Stop("Esri HQ", latlng);
var home = new L.esri.Routing.Stop("Home", latlng);

var myRoute = new L.esri.Routing.Route()
                .stop(esrihq)
                .stop(home)
                .addTo(map);

// when you drag a marker around automatically update
esriMarker.on('dragend', function(e){
  var start = new L.esri.Routing.Stop("Esri HQ", e.latlng)
                  .allowUTurn(false) // allow a u turn at this stop
                  .approchFrom('right'); // only approach this stop from the right

// lookup the named stop in the stops and update rather then create it.
myRoute.stop(start);
}
```

Maybe this is all to much work though and we should skip live update for the first version. I still haven't thought of a way to get around the events issue.

> robust samples (including turning addresses into stops) seem pretty essential.

Things brings up something else I've thought a lot about. I firmly believe that this plugin shouldn't allow using addresses as stops. If you want to do this you should have yourself with the geocoding plugin.

My main reason for this is that just pulling the first address out of the geocoding is hit and miss. Take for example this address.

620 SW Taylor St. If you drop this in the geocoder it will return a lot of non specific results and the first one might not necessary be the one you want. If we accept addresses in the input it also raises a lot of implementation questions, what about options? what if I want to use my own geocoder?

> i assume we will get a substantial number of requests and i think it would be pretty awesome/useful if developers could substitute their own network analyst services via an optional constructor parameter.

This can be handled pretty easily like in the geocoder plugin.

``` js
var route = new Route(options) // uses arcgis online routing service

var route = new Route(url, options) // uses your network analyst service
```

**Comment by jgravois** [comment]
sounds like we're on the same page.  

i'm all for exposing any and all parameters which differentiate us from other SAS offerings.  i probably didn't articulate it very well, but i guess my first instinct is to make sure that developers first encounter with samples and API reference highlights the parameters that they _need_ to provide values for and differentiates everything else as optional (with sensible defaults)

with regard to a sample which incorporates geocoding, i fully expected that it would leverage a seperate plugin..

**Comment by jgravois** [comment]
cc/ @markstos .  please check out the README for this new repo when you have a moment, i'd be curious to hear your feedback.

**Comment by markstos** [comment]
Thanks for keeping me in the loop. Are you targeting use by frontend or backend JavaScript with this, or both?

Leaflet sounds like would be for frontend maps. But if it's frontend code, how would you handle authentication for paid services, since you wouldn't want to put private credentials on frontend code?

**Comment by jgravois** [comment]
esri leaflet developers have a couple different options when exposing subscription routing services.
1. When the target audience has ArcGIS Online Organizational subscription credentials, the app can use OAuth to allow end users to authenticate directly with arcgis.com and burn their own credits.  see [this](https://esri.github.io/esri-leaflet/examples/premium-content.html) example.
2. Alternatively, if a developer wants the app itself to provide authentication, the recommended approach is to utilize a server side [proxy](https://github.com/esri/resource-proxy) so that neither a token nor credentials are exposed in code.  we don't have an esri leaflet sample of this, but the approach would be similar to [this](https://developers.arcgis.com/javascript/jssamples/widget_directions_basic.html).  for example [FeatureLayer](http://esri.github.io/esri-leaflet/api-reference/layers/feature-layer.html) includes a constructor option which allows you to identify your proxy.

**Comment by patrickarlt** [comment]
> Are you targeting use by frontend or backend JavaScript with this, or both?

I'm only targeting front-end developers using Leaflet for this. There are a few reasons...
1. We can directly build off of `L.esri.Service` and `L.esri.Task` as well as the low level `L.esri.request` methods
2. It limits scope to something manageable. Early versions of Geoservices JS supported both node and browser quickly became to unwieldily and difficult to build and test. The narrow scope will help make this project manageable.
3. It provides an opportunity to deliver a unique API since we can also handle rendering, popups and events for developers not just a request/response wrapper.

To add to what @jgravois said above a third option would be to generate a short lived token on the server (something like 30 minutes) and pass it down to the client. You could control access to the token generation endpoint with a Referer whitelist (I know it can be faked but it helps) or whatever other method you want.

We will also be adding some new features to the developers site in March that will make accomplishing option 2 from @jgravois above MUCH easier.

**Comment by markstos** [comment]
Thanks for the feedback. Sounds like a good approach!
