### ISSUE TITLE
Ability to set popup content for the route (line) element

### ISSUE THREAD

**Issue by alaframboise** [Esri/esri-leaflet-routing#10]
It's not clear if there will be a callback function or someway to set custom content for the popup for the actual line route element.  I can see wanting to hover over the route element and wanting to get a specific route information for each route returned.

Popups on the Route

var myRoute = new L.esri.Routing.Route()
                .start(latlng)
                .bindStartPopup(function)
                .end(latlng)
                .bindEndPopup(function)
                .stop(latlng)
                .bindStopPopup(function)
.bindRoutePopup(function)  // popup for line
                .addTo(map);

**Comment by patrickarlt** [comment]
Given my new thinking in https://github.com/Esri/esri-leaflet-routing/issues/3 and https://github.com/Esri/esri-leaflet-routing/issues/4 this would probably mean that route would expand/encapsulate Polyline which means you would be able to bind popups to it.

**Comment by patrickarlt** [comment]
This means that you would now have 4 distinct objects and be able to bind a popup to each.

``` js
var home = new L.esri.Routing.Stop(latlng, {
    name:  'Home'
});

var caffeine = new L.esri.Routing.Stop(latlng, {
    name:  'Augies'
}).uTurn(false).approchFrom('Right');

var work = new L.esri.Routing.Stop(latlng, {
    name:  'Esri HQ'
});

var route = new L.esri.Routing.Route().start(home).stop(caffeine).end(work).addTo(map);
```
