### ISSUE TITLE
Should ClosestFacility be called something else?

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet-routing#2]
Since the current proposal for ClosestFacility makes no references to facilities or incidents should it be named something else? `Closest`, `ClosestPlace`, `ClosestDestination`?

**Comment by jgravois** [comment]
`Closest` sounds good to me.

**Comment by patrickarlt** [comment]
I'm going to go with `ClosestDestination` for now.

What was the reasoning behind `Closest`?

**Comment by jgravois** [comment]
i like the brevity, but ClosestDestination is probably clearer.
