### ISSUE TITLE
Should you be able to add Stops, Origins and Destinations to the map?

### ISSUE THREAD

**Issue by patrickarlt** [Esri/esri-leaflet-routing#3]
Currently there are 3 classes `Stop`, `Origin`, `Destination` that we would have to add to the map and manage along with the routes for things like `Route` and `ClosestFacility`. Would it be easier to do this?

``` js
// L.esri.routing.Destination extends Marker? Easier API but you cant use things like circle marker
var hospital1 = new L.esri.routing.Destination(latlng, {
  name: "hospital 1",
  icon: someIcon
}).allowUTurn(false).addTo(map);

// or do we have a function to create the marker? means you can use anything that can be added to the map
var hospital2 = new L.esri.routing.Destination(latlng, {
  name: "hospital 2",
  marker: L.marker(...)
}).allowUTurn(false);

var accident = new L.esri.routing.Origin('Accident').closest(2).maxTravelTime(60).addTo(map); // choose the 2 closest destinations but ignore destinations that will take over 60 minutes to get to

// now the L.esri.routing.ClosestFacility() just adds the polyline to the map not the markers.
var route = new L.esri.routing.ClosestFacility().origin(Accident).destination(hospital1).destination(hospital2).destination(hospital2).addTo(map);
```

The approach would make it easier to bind events to the stops and routes since you would do everything separately.

**Comment by jgravois** [comment]
seems like it might be cumbersome if a developer had a significant number of facilities.

perhaps something like `destinations( [ ] )` would be sufficient to help though?

**Comment by patrickarlt** [comment]
I'm thinking the the `Stop`, `Origin`, `Destination` classes are 2 things.
1. Extensions of marker do they can have events, popups ect...
2. Param helpers for building things with U turn restrictions, curb approaches, ect...

if you want neither of those things the shorthand `stop(latlng, "name")`, `destination(latlng, "name")`, `origin(latlng, "name")` will serve you just fine.

Should we also include a `destinations( [ ] )` short hand that can just take an array of latlng or an array of `Stop/Origin/Destination` objects? Nothing is forcing you add them to the map since you can also just use `route.run()` to get the raw geojson if you want to parse the results yourself.

I'm trying to work through all of this since I hate the idea of having `ClosestFacilityService` and `ClosestFacilityDrawingThing` as separate classes.

**Comment by patrickarlt** [comment]
Agreed in #7 that there should be a `stops()` method for setting multiple stops up at once. It follows that there should be an `origins()` and `destinations()` and `barriers()` methods as well.

**Comment by patrickarlt** [comment]
This is generally the path that I am currently working on now.
