### ISSUE TITLE
Inspect routing results before adding to map

### ISSUE THREAD

**Issue by alaframboise** [Esri/esri-leaflet-routing#6]
It's essential to be able to inspect routing results before adding them to the map.  Users might have some other criteria not defined in the route service e.g. route cannot be too close to Starbucks and it needs to be augmented. I assume a callback will be exposed to handle this.

**Comment by nixta** [comment]
+1

Perhaps a final deferred should receive the route result object, which should have an `addToMap()` function on it.

``` JavaScript
var myRoute = L.esri.Routing.Route().from(A).to(B).then(function (directions) {
  if (/* directions are ok */) {
    directions.addToMap(myMap);
  } else {
    // Oh dear
  }
}).fail(function (error) {
  // Uh oh
});
```

**Comment by patrickarlt** [comment]
Routes are still tasks which mean would be able to `run` them as follows

``` js
var myRoute = L.esri.Routing.Route().start(A).end(B).run(function (error, geojson) {
 // figure out if route is on render it on map yourself using L.GeoJSON or myRoute.addTo(map);
});
```

Search the original document for Accessing "Raw Route Data" to see this in action.
