### ISSUE TITLE
Pass in an array for multiple stops

### ISSUE THREAD

**Issue by alaframboise** [Esri/esri-leaflet-routing#7]
Might be better to be able to pass in an array of stop points.

Optimize Multiple Stops

// if optimize is true start() and end() will preserve first last stops
var myRoute = new L.esri.Routing.Route({
    optimize: true,
}).start(latlng).stops([pt1,pt2,pt3]).end(latlng).addTo(map);

**Comment by nixta** [comment]
+1

With multiple stops, the proposed model would become very unqeildy quickly. A stop could either be a Stop object or a lat/lng that gets turned into a Stop object internally (since I think you were planning on having Stop objects handle popup bindings and the like).

**Comment by patrickarlt** [comment]
agreed a `stop(*/stop or latlng*/)` and `stops(*/array of stops or latlngs*/)` method makes sense as 3 people have proposed it @alaframboise, @nixta and @jgravois.
